export const ApiUrls = {
  CATEGORIES: "/ceo/categories",
  BRANDS: "/ceo/brands",
  TIME: "/ceo/time",
  // MARKETING: "/endpoint_url/ceo/marketing",
  SALES: "/ceo/sales",
  PROFIT_LOSS: "/ceo/profit_loss",
  PROMOTION: "/ceo/promotion",
  MARKETING: "/ceo/marketing",

  CHANNELS: "/tradepromotion/channels",
  PRODUCTS: "/tradepromotion/products",
  BUDGET: "/tradepromotion/budget",
  TOP_CHANNELS: "/tradepromotion/top_channels",
  LOW_CHANNELS: "/tradepromotion/low_channels",
  CHANNEL_WISE_SPEND: "/tradepromotion/channel_wise_spend",
  PRODUCT_WISE_SPEND: "/tradepromotion/product_wise_spend",
  NO_CONSTRAINTS__SCREEN: "/tradepromotion/no_constraint",
  ON_TRACK: "/tradepromotion/ontrack",
  OPTIMISATION: "/tradepromotion/optimisation",
  UNDER_HOOD: "/tradepromotion/under_hood",

  DISTRIBUTION_DIVERGENCE: "/teresa/divergence",
  TERESA_SALES: "/teresa/sales",
  TERESA_GEO: "/teresa/geo",
  TERESA_TIMESERIES: "/teresa/sales_timeseries",
  TERESA_MODELS_PRODUCTS: "/teresa/models_with_products",
  TERESA_REGIONS: "/teresa/regions",
  TERESA_BRANDS: "/teresa/region_brands",
  TERESA_FORECAST: "/teresa/baseline_forecast",
  TERESA_PRODUCT_DIVE: "/teresa/product_deep_dive",
  TERESA_ATTRIBUTION: "/teresa/attribution",
  PRODUCTS_WITHOUT_CHANNELS: "/tradepromotion/products_without_channel",
  CHANGE_DATA_CHANNEL: "/tradepromotion/change_data_channel",
  ALFRED_SALES_DATA:"/alfred/sales",
  ALFRED_CROSSSALES_DATA:"/alfred/cross_sell",
  ALFRED_TABLE_DATA:"/alfred/detailed_data",
  EASY_TO_EARN:"/alfred/easy_to_earn",
  ALFRED_TOPOUTLETS_DATA:"/alfred/top_outlet",
  ALFRED_LEASTOUTLETS_DATA:"/alfred/less_outlet",
  NEPTUNE_BRANDS: "/neptune/brands",
  NEPTUNE_BRANDS_DETAIL: "/neptune/brand_detail",
  NEPTUNE_EDA: "/neptune/eda",
  NEPTUNE_SALES: "/neptune/sales",
  NEPTUNE_PERFORMANCE: "/neptune/campaign_performace",
  NEPTUNE_CAMPAIGN: "/neptune/campaign",
  NEPTUNE_CHANNEL: "/neptune/channel",
  NEPTUNE_SPENDS_ROMI: "/neptune/spends_romi",
  NEPTUNE_THREE_MONTHS_AVG_SPEND:"/neptune/three_month_avg_spend",
  ROMI_SIMULATION:"/neptune/spends_romi_simulation",
  CUSTOM_MAP: "/alfred/map_planning",
  LAST_MONTHS_SALES:"/neptune/last3monthssales"
};
