import { ImageUtils } from "../../utils/ImageUtils";

//Normal Data
const data = [
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_values_spends: "23 K",
    current_values_sales: "120 K",
    current_values_ROI: "5.7",
    recommended_values_spends: "23 K",
    recommended_values_sales: "120 K",
    recommended_values_ROI: "5.7",
    flag: 1,
  },
];

const productHeader = [
  {
    field: "product",
    header2: "Product",
  },
  {
    field: "channel",
    header2: "Channel",
  },
];

const currentHeader = [
  {
    field: "current_values_spends",
    header1: "Current Values",
    header2: "Spends",
  },
  {
    field: "current_values_sales",
    header1: "Current Values",
    header2: "Sales",
  },
  {
    field: "current_values_ROI",
    header1: "Current Values",
    header2: "ROI",
  },
];

const recommendedHeader = [
  {
    field: "recommended_values_spends",
    header1: "Recommended Values",
    header2: "Spends",
  },
  {
    field: "recommended_values_sales",
    header1: "Recommended Values",
    header2: "Sales",
  },
  {
    field: "recommended_values_ROI",
    header1: "Recommended Values",
    header2: "ROI",
  },
];

// Channel Wise Data
const channelWiseData = [
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_product_1: "120 K",
    current_spends_product_2: "5.7",
    current_spends_product_3: "5.7",
    current_spends_product_4: "5.7",
    current_spends_product_5: "5.7",
    proposed_spends: "23 K",
    recommended_spends_product_1: "23 K",
    recommended_spends_product_2: "120 K",
    recommended_spends_product_3: "5.7",
    recommended_spends_product_4: "5.7",
    recommended_spends_product_5: "5.7",
    revised_ROI: "5.7",
    flag: 1,
  },
];

const channelWiseProductHeader = [
  {
    field: "channel",
    header2: "Channel",
  },
];

const channelWiseCurrentHeader = [
  {
    field: "current_spends_total_spends",
    header1: "Current Spends",
    header2: "Total Spends",
  },
  {
    field: "current_spends_product_1",
    header1: "Current Spends",
    header2: "Product 1",
  },
  {
    field: "current_spends_product_2",
    header1: "Current Spends",
    header2: "Product 2",
  },
  {
    field: "current_spends_product_3",
    header1: "Current Spends",
    header2: "Product 3",
  },
  {
    field: "current_spends_product_4",
    header1: "Current Spends",
    header2: "Product 4",
  },
  {
    field: "current_spends_product_5",
    header1: "Current Spends",
    header2: "Product 5",
  },
];

const channelWiseMiddleStartHeader = [
  {
    field: "proposed_spends",
    header2: "Proposed Spends",
  },
];

const channelWiseRecommendedHeader = [
  {
    field: "recommended_spends_product_1",
    header1: "Recommended Spends",
    header2: "Product 1",
  },
  {
    field: "recommended_spends_product_2",
    header1: "Recommended Spends",
    header2: "Product 2",
  },
  {
    field: "recommended_spends_product_3",
    header1: "Recommended Spends",
    header2: "Product 3",
  },
  {
    field: "recommended_spends_product_4",
    header1: "Recommended Spends",
    header2: "Product 4",
  },
  {
    field: "recommended_spends_product_5",
    header1: "Recommended Spends",
    header2: "Product 5",
  },
];

const channelWiseMiddleEndHeader = [
  {
    field: "revised_ROI",
    header2: "Revised ROI",
  },
];

//Product Wise
const productWiseData = [
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    current_spends_total_spends: "23 K",
    current_spends_krogers: "120 K",
    current_spends_walmart: "5.7",
    proposed_spends: "23 K",
    recommended_spends_krogers: "23 K",
    recommended_spends_walmart: "120 K",
    revised_ROI: "5.7",
    flag: 1,
  },
];

const productWiseProductHeader = [
  {
    field: "product",
    header2: "Product",
  },
];

const productWiseCurrentHeader = [
  {
    field: "current_spends_total_spends",
    header1: "Current Spends",
    header2: "Total Spends",
  },
  {
    field: "current_spends_krogers",
    header1: "Current Spends",
    header2: "Krogers",
  },
  {
    field: "current_spends_walmart",
    header1: "Current Spends",
    header2: "Walmart",
  },
];

const productWiseMiddleStartHeader = [
  {
    field: "proposed_spends",
    header2: "Proposed Spends",
  },
];

const productWiseRecommendedHeader = [
  {
    field: "recommended_spends_krogers",
    header1: "Recommended Spends",
    header2: "Krogers",
  },
  {
    field: "recommended_spends_walmart",
    header1: "Recommended Spends",
    header2: "Walmart",
  },
];

const productWiseMiddleEndHeader = [
  {
    field: "revised_ROI",
    header2: "Revised ROI",
  },
];

//Curve Data
const curveData = [
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: 1,
  },
  {
    id: 1,
    product_image: ImageUtils.DrinkCan,
    product: "Product 1",
    channel_image: ImageUtils.Kroger,
    channel: "Krogers",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: -1,
  },
  {
    id: 2,
    product_image: ImageUtils.Chocolate,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: 0,
  },
  {
    id: 3,
    product_image: ImageUtils.Chips,
    product: "Product 1",
    channel_image: ImageUtils.WalmartIcon,
    channel: "Wallmart",
    spends: "23 K",
    recommended_spends: "120 K",
    roi_change: "5.7",
    uplift: [100, 200, 300, 400, 500],
    roi: [6, 6.2, 6.8, 7, 9],
    data: [210, 290, 400, 420, 450],
    spends_graph: [25, 30, 35, 40, 45],
    flag: 1,
  },
];

const curveProductHeader = [
  {
    field: "product",
    header2: "Product",
  },
  {
    field: "channel",
    header2: "Channel",
  },
  {
    field: "spends",
    header2: "Spends",
  },
  {
    field: "recommended_spends",
    header2: "Recommended Spends",
  },
  {
    field: "roi_change",
    header2: "ROI Change",
  },
];

const initialState = {
  tableData: {
    data: data,
    productHeader: productHeader,
    currentHeader: currentHeader,
    recommendedHeader: recommendedHeader,
  },
  channelWiseData: {
    data: channelWiseData,
    productHeader: channelWiseProductHeader,
    currentHeader: channelWiseCurrentHeader,
    middleStartHeader: channelWiseMiddleStartHeader,
    recommendedHeader: channelWiseRecommendedHeader,
    middleEndHeader: channelWiseMiddleEndHeader,
  },
  productWiseData: {
    data: productWiseData,
    productHeader: productWiseProductHeader,
    currentHeader: productWiseCurrentHeader,
    middleStartHeader: productWiseMiddleStartHeader,
    recommendedHeader: productWiseRecommendedHeader,
    middleEndHeader: productWiseMiddleEndHeader,
  },
  curveData: {
    data: curveData,
    productHeader: curveProductHeader,
  },
};

const tpOptimisationReducer = (state = initialState, action) => {
  switch (action.type) {
    case "SET_TABLE_DATA":
      return { ...state, ...action.payload };
    default:
      return state;
  }
};

export default tpOptimisationReducer;
